theme: jekyll-theme-cayman
title: Tess Robertson
description: Software developer with a passion for problem solving located in Vancouver, BC. Graduated from the Computer Systems Technology program at BCIT in 2016.
