theme: jekyll-theme-cayman
title: Tess Robertson
description: Software developer with a passion for problem solving. Located in Vancouver, BC. Graduate of the Computer Systems Technology program at BCIT.
github:
  repository_url: http://github.com/tessrobertson
